name: asset_fill
description: A package to generate assets in pubspec.yaml. Goes throw all the subdirectories in assets folder.
version: 1.0.1
repository: https://github.com/L3odr0id/asset_fill

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml_edit: ^2.0.1
  # yaml_writer: ^1.0.1
  # yaml: ^3.1.0
  # yaml_fluency: ^2.1.0

