name: asset_fill
description: A package generate assets in pubspec.yaml
version: 1.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml_edit: ^2.0.1
  # yaml_writer: ^1.0.1
  # yaml: ^3.1.0
  # yaml_fluency: ^2.1.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

